### ISSUE TITLE
`npm install -g ptbk` fails on Node 26 (better-sqlite3 has no prebuilt binary and does not compile)

### ISSUE THREAD

**Issue by JorgeSquared** [webgptorg/promptbook#329]
**Version:** `ptbk` 0.114.0-26, Node 26.7.0, macOS arm64, Xcode CLT present.

`better-sqlite3` (transitive dependency) falls back to `node-gyp rebuild` and fails:

```
./src/util/binder.lzz:40:37: error: no member named 'GetPrototype' in 'v8::Object'; did you mean 'GetPrototypeV2'?
./src/objects/database.lzz:416:89: error: no member named 'This' in 'v8::PropertyCallbackInfo<v8::Value>'
```

Works on Node 22.23.2. Either bump `better-sqlite3` to a release with Node 26 support, make it optional, or declare `engines.node` so npm warns early.

**Comment by hejny** [comment]
@JorgeSquared Please create PRDs directly or as pull request:

*(I have done it from this issue)*
https://github.com/webgptorg/promptbook/commit/095663cc6ce8d4f275c199314095b8fe079c1c65
